name: Node CI

on:
  push:
    branches:
    - master

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: test action
      run: |
        npm install 
        npm run build
